[font]
builtin_box_drawing = true
size = 13.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[scrolling]
history = 100000
multiplier = 6

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
dynamic_title = true
opacity = 1
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[colors.primary]
background = "#1e222a"
foreground = "#c8ccd4"

[colors.cursor]
text = "#1e222a"
cursor = "#abb2bf"

[colors.selection]
text = "#1e222a"
background = "#c8ccd4"

[colors.normal]
black = "#1e222a"
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#abb2bf"

[colors.bright]
black = "#545862"
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#c8ccd4"

[terminal]

[terminal.shell]
program = "/bin/sh"
args = ["-lc", "command -v fish >/dev/null 2>&1 && exec fish || exec bash"]
