# vim: foldmethod=marker

backend = "glx";
vsync = true;
use-damage = true;
unredir-if-possible = false;

fading = false;

shadow = false;
blur-method = "none";
blur-background = false;
blur-background-frame = false;
blur-background-fixed = false;

active-opacity = 1.0;
inactive-opacity = 1.0;
frame-opacity = 1.0;
opacity-rule = [];

corner-radius = 0;
