foreground #e0e2ef
background #10131c
cursor #b3c5ff
cursor_text_color #002a77
selection_foreground #2e2d4d
selection_background #c5c3ea
url_color #b3c5ff

color0 #1d1f29
color1 #ffb4ab
color2 #d1bdf6
color3 #c5c3ea
color4 #b3c5ff
color5 #d1bdf6
color6 #c5c3ea
color7 #e0e2ef
color8 #8e909c
color9 #ffb4ab
color10 #d1bdf6
color11 #c5c3ea
color12 #b3c5ff
color13 #d1bdf6
color14 #c5c3ea
color15 #e0e2ef
