;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;==========================================================

[global/wm]
include-file = $HOME/.config/polybar/colors.ini
include-file = $HOME/.config/polybar/modules.ini

; Setting up the main laptop monitor
[bar/top]
monitor = ${env:MONITOR:eDP}
width = 1886
height = 34
radius = 13
padding-left = 2
padding-right = 2
module-margin = 1
background = ${colors.background}
foreground = ${colors.foreground}
bottom = false
override-redirect = true
border-size = 0
offset-x = 16
offset-y = 10
fixed-center = true
line-size = 2
wm-restack = bspwm

modules-left = filesystem bspwm
modules-center = temperature memory cpu
modules-right = xkeyboard battery time

font-0 = JetBrainsMono Nerd Font:style=Medium:pixelsize=12;3
font-1 = JetBrainsMono Nerd Font:size=16;4
font-2 = JetBrainsMono Nerd Font:style=Bold:size=12;3
font-3 = Noto Sans:size=12:antialias=true;3
font-4 = JetBrainsMono Nerd Font:style=Bold:size=20;5

[bar/top-external]
inherit = bar/top
width = 3806
height = 46
radius = 17
offset-y = 12
padding-left = 2
font-0 = JetBrainsMono Nerd Font:style=Medium:pixelsize=18;5
font-1 = JetBrainsMono Nerd Font:size=24;7
font-2 = JetBrainsMono Nerd Font:style=Bold:size=18;5
font-3 = Noto Sans:size=18:antialias=true;5
font-4 = JetBrainsMono Nerd Font:style=Bold:size=30;8
