
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;      __  ___          __      __
;     /  |/  ____  ____/ __  __/ ___  _____
;    / /|_/ / __ \/ __  / / / / / _ \/ ___/
;   / /  / / /_/ / /_/ / /_/ / /  __(__  )
;  /_/  /_/\____/\__,_/\__,_/_/\___/____/
;
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/round-left]
type = custom/text
format = %{T3} %{T-}
format-foreground = ${colors.surface}

[module/round-right]
type = custom/text
format = %{T3}%{T-}
format-foreground = ${colors.surface}

[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 70

format = <ramp> <label>
format-warn = <ramp> <label-warn>
format-padding = 1
label = %temperature-c%
label-warn = %temperature-c%
ramp-0 = ""
ramp-foreground = ${colors.color6}
label-foreground = ${colors.foreground}
label-warn-foreground = ${colors.error}

[module/bspwm]
type = internal/bspwm

pin-workspaces = false
inline-mode = true
enable-click = true
enable-scroll = true
reverse-scroll = false

format = <label-state>
ws-icon-0 = 1;1
ws-icon-1 = 2;2
ws-icon-2 = 3;3
ws-icon-3 = 4;4
ws-icon-4 = 5;5

label-separator = ""

label-focused = %icon%
label-focused-foreground = #C8CCD4
label-focused-underline = #1793D1
label-focused-padding = 2

label-occupied = %icon%
label-occupied-foreground = #C8CCD4
label-occupied-padding = 2

label-empty = %icon%
label-empty-foreground = #C8CCD4
label-empty-padding = 2

label-urgent = %icon%
label-urgent-foreground = ${colors.error}
label-urgent-underline = ${colors.error}
label-urgent-padding = 2

[module/alsa]
type = internal/pulseaudio
use-ui-max = false
format-volume = <ramp-volume> <label-volume>
format-volume-padding = 1
format-muted = 󰖁
format-muted-padding = 1
label-volume = %percentage%%
ramp-volume-0 = 󰖀
ramp-volume-1 = 󰖀
ramp-volume-2 = 󰖀
ramp-volume-3 = 󰖀
ramp-volume-4 = 󰖀
ramp-volume-5 = 󰕾
ramp-volume-6 = 󰕾
ramp-volume-7 = 󰕾
ramp-volume-8 = 󰕾
ramp-volume-9 = 󰕾
ramp-headphones-0 = 
ramp-headphones-1 = 
format-volume-foreground = ${colors.foreground-right}
ramp-volume-foreground = ${colors.foreground-right}
label-volume-foreground = ${colors.foreground-right}
format-muted-foreground = ${colors.foreground-right}

[module/time]
type = internal/date
interval = 60
format = <label>
format-padding = 1
date = %a %d %b  %H:%M
label = %date%
label-foreground = #FFFFFF

[module/timer]
type = custom/script
exec = ${env:HOME}/.local/bin/timer status
interval = 1
format = <label>
label = %output%
click-left = ${env:HOME}/.local/bin/timer menu
click-right = ${env:HOME}/.local/bin/timer cancel

[module/memory]
type = internal/memory
interval = 2
format = <label>
format-prefix = " "
format-padding = 1
format-foreground = #D19A66
label = %gb_used%

[module/filesystem]
type = custom/text 
format = "%{T5}%{T-}"
format-padding = 2
click-left = powermenu
format-foreground = #1793D1

[module/ethernet]
type = internal/network
interface = enp5s0
format-connected = <label-connected>
format-connected-prefix = "󰈁 "
format-connected-padding = 1
format-disconnected = <label-disconnected>
format-disconnected-prefix = "󰈂 "
format-disconnected-padding = 1
label-connected = "%{A1:nm-connection-editor &:}%downspeed%|%upspeed%%{A}"
label-disconnected =

[module/battery]
type = internal/battery
full-at = 98
low-at = 10

battery = BAT0
adapter = AC
poll-interval = 5

time-format = %H:%M
format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-full = <ramp-capacity> <label-full>
format-low = <label-low> <animation-low>
format-charging-padding = 1
format-discharging-padding = 1
format-full-padding = 1
format-low-padding = 1

label-charging = %percentage%%
label-discharging = %percentage%%
label-full = 100%
label-low = %percentage%

ramp-capacity-0 = " "
ramp-capacity-1 = " "
ramp-capacity-2 = " "
ramp-capacity-3 = " "
ramp-capacity-4 = " "
bar-capacity-width = 10

animation-charging-0 = " "
animation-charging-1 = " "
animation-charging-2 = " "
animation-charging-3 = " "
animation-charging-4 = " "
animation-charging-framerate = 910

animation-discharging-0 = " "
animation-discharging-1 = " "
animation-discharging-2 = " "
animation-discharging-3 = " "
animation-discharging-4 = " "
animation-discharging-framerate = 500

animation-low-0 = "  "
animation-low-1 = "  "
animation-low-framerate = 1500

animation-low-foreground = ${colors.error}
format-charging-foreground = ${colors.primary}
label-charging-foreground = ${colors.primary}
format-discharging-foreground = ${colors.foreground-right}
label-discharging-foreground = ${colors.foreground-right}
format-full-foreground = ${colors.success}
label-full-foreground = ${colors.success}
format-low-foreground = ${colors.error}
label-low-foreground = ${colors.error}
format-full-prefix-foreground = ${colors.success}
ramp-capacity-foreground = ${colors.foreground-right}
animation-charging-foreground = ${colors.primary}

[module/backlight]
type = internal/backlight
card = amdgpu_bl1
use-actual-brightness = true
enable-scroll = true
scroll-interval = 5
format = <label>
format-prefix = " "
format-prefix-foreground = ${colors.foreground-right}
label-foreground = ${colors.foreground-right}
format-padding = 1
label = %percentage%%

[module/powermenu]
type = custom/text 
format = " "
format-padding = 1
click-left = powermenu
format-foreground = ${colors.error}

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " " 
format = <label>
label = %percentage%%
format-foreground = #989CFF

[module/xwindow]
type = internal/xwindow
label = %title:0:30:...

[module/space]
type = custom/text
format = " "

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
blacklist-1 = scroll lock
format = <label-layout> <label-indicator>
format-padding = 1
label-layout-foreground = ${colors.foreground-right}
label-layout = %icon%
label-indicator-on = %name%
layout-icon-default = 
layout-icon-0 = us;us
layout-icon-1 = ru;ru
layout-icon-2 = ructrl;ru
label-indicator-on-capslock = !
label-indicator-off-capslock =
